[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "endstone-ushop"
version = "250812"
description = "A powerful shop system plug-in for endstone server..."

[project.entry-points."endstone"]
ushop = "endstone_ushop:ushop"